const js = require('@eslint/js');
const globals = require('globals');

module.exports = [
    js.configs.recommended,
    {
        languageOptions: {
            globals: {
                ...globals.node,
                ...globals.es6
            },
            ecmaVersion: 2020,
            sourceType: 'commonjs'
        },
        rules: {
            'comma-dangle': ['error', 'never'],
            'no-console': 'off',
            'no-constant-condition': 'error',
            'no-control-regex': 'error',
            'no-debugger': 'warn',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-empty-character-class': 'error',
            'no-empty': 'error',
            'no-extra-boolean-cast': 'error',
            'no-extra-semi': 'error',
            'no-func-assign': 'error',
            'no-inner-declarations': 'error',
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': 'error',
            'no-unreachable': 'error',
            'use-isnan': 'error',
            'valid-typeof': 'error',
            'accessor-pairs': 'error',
            'block-scoped-var': 'error',
            'curly': 'error',
            'default-case': 'error',
            'dot-location': ['error', 'property'],
            'dot-notation': 'error',
            'eqeqeq': ['error', 'smart'],
            'no-alert': 'warn',
            'no-caller': 'error',
            'no-case-declarations': 'error',
            'no-div-regex': 'warn',
            'no-else-return': 'error',
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-fallthrough': 'error',
            'no-floating-decimal': 'error',
            'no-implied-eval': 'error',
            'no-iterator': 'error',
            'no-labels': 'error',
            'no-lone-blocks': 'error',
            'no-loop-func': 'error',
            'no-multi-spaces': 'error',
            'no-multi-str': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-new': 'error',
            'no-octal-escape': 'error',
            'no-octal': 'error',
            'no-param-reassign': 'error',
            'no-proto': 'error',
            'no-redeclare': 'error',
            'no-return-assign': 'error',
            'no-self-compare': 'error',
            'no-throw-literal': 'error',
            'no-unused-expressions': ['error', { 'allowShortCircuit': true }],
            'no-useless-call': 'error',
            'no-useless-concat': 'error',
            'no-void': 'error',
            'no-warning-comments': 'warn',
            'no-with': 'error',
            'radix': 'warn',
            'vars-on-top': 'error',
            'wrap-iife': ['error', 'inside'],
            'yoda': 'error',
            'strict': 'off',
            'no-delete-var': 'error',
            'no-shadow-restricted-names': 'error',
            'no-shadow': 'error',
            'no-undef-init': 'error',
            'no-unused-vars': 'error',
            'no-use-before-define': ['error', { 'functions': true, 'classes': false, 'variables': true }],
            'global-require': 'error',
            'handle-callback-err': 'warn',
            'no-new-require': 'error',
            'array-bracket-spacing': ['warn', 'never'],
            'block-spacing': ['error', 'always'],
            'brace-style': ['error', '1tbs', { 'allowSingleLine': false }],
            'camelcase': ['error', { 'properties': 'always' }],
            'comma-spacing': ['error', { 'before': false, 'after': true }],
            'comma-style': ['error', 'last'],
            'computed-property-spacing': ['warn', 'never'],
            'consistent-this': ['error', 'self'],
            'eol-last': 'error',
            'func-style': ['error', 'expression'],
            'indent': ['error', 4, { 'SwitchCase': 1 }],
            'key-spacing': ['error', { 'beforeColon': false, 'afterColon': true }],
            'new-cap': 'error',
            'new-parens': 'error',
            'no-array-constructor': 'error',
            'no-bitwise': 'error',
            'no-continue': 'error',
            'no-lonely-if': 'error',
            'no-mixed-spaces-and-tabs': 'error',
            'no-multiple-empty-lines': ['error', { 'max': 2, 'maxEOF': 1 }],
            'no-nested-ternary': 'error',
            'no-new-object': 'error',
            'no-trailing-spaces': ['error', { 'skipBlankLines': true }],
            'no-unneeded-ternary': 'error',
            'object-curly-spacing': ['error', 'always'],
            'operator-linebreak': ['error', 'after', { 'overrides': { '?': 'before', ':': 'before' } }],
            'quotes': ['warn', 'single', { 'allowTemplateLiterals': true }],
            'semi': ['error', 'always'],
            'keyword-spacing': ['error', { 'before': true, 'after': true }],
            'space-before-blocks': ['error', 'always'],
            'space-before-function-paren': ['error', 'never'],
            'space-in-parens': ['warn', 'never'],
            'space-infix-ops': 'error',
            'space-unary-ops': ['error', { 'words': true, 'nonwords': false }],
            'spaced-comment': ['error', 'always'],
            'arrow-parens': ['error', 'always'],
            'arrow-spacing': 'error',
            'constructor-super': 'error',
            'generator-star-spacing': ['error', { 'before': true, 'after': false }],
            'no-confusing-arrow': 'error',
            'no-class-assign': 'error',
            'no-const-assign': 'error',
            'no-dupe-class-members': 'error',
            'no-this-before-super': 'error',
            'no-var': 'error',
            'prefer-spread': 'warn',
            'prefer-template': 'warn',
            'require-yield': 'error'
        }
    },
    {
        files: ['test/**/*.js'],
        languageOptions: {
            globals: {
                ...globals.mocha
            }
        }
    },
    {
        files: ['views/**/*.js'],
        languageOptions: {
            globals: {
                ...globals.browser,
                ...globals.jquery
            }
        }
    }
];
